### ISSUE TITLE
Update README with more details

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-local-notification#1]

**Comment by williamle8300** [comment]
If this is a plugin to send notifications without using APNS or Google's Push Notifications services... there definitely needs to be more documentation. Currently, I don't see anything to help me dispatch notifications...

**Comment by dpogue** [comment]
This is for local notifications created and shown by code running on the device, not for push notifications which can be triggered remotely.

**Comment by chauthai** [comment]
More info can be found here: https://blog.phonegap.com/release-of-phonegap-local-notification-plugin-bc7f480b6fd6
