### ISSUE TITLE
not restart app

### ISSUE THREAD

**Issue by devjva** [phonegap/phonegap-plugin-local-notification#18]
#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-local-notification   # e.g. 1.5.3

**Comment by maverickmishra** [comment]
Closing this issue for the lack of details. Please feel free to re-open with necessary details provided in the template if the issue is still not resolved.
